/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{league_tag}/current-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Round */
        get: operations["current_round_v1_leagues__league_tag__current_round_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leagues/{league_tag}/events/{event_tag}/rounds/{round_number}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Round Matches By Slug */
        get: operations["round_matches_by_slug_v1_leagues__league_tag__events__event_tag__rounds__round_number__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Match Result */
        put: operations["set_match_result_v1_matches__match_id__result_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rounds/{round_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Round Matches By Id */
        get: operations["round_matches_by_id_v1_rounds__round_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CurrentRoundDTO */
        CurrentRoundDTO: {
            /** Event Name */
            event_name: string;
            /** Event Tag */
            event_tag: string;
            /** League Tag */
            league_tag: string;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * EventRoundDTO
         * @description Summary of one round in an Event, used by the round navigator at the
         *     top of round-scoped pages. ``is_published`` mirrors the Django
         *     ``Round.publish_pairings`` flag — pairings are visible to the public
         *     only when this is true; the UI fades unpublished (future) rounds.
         */
        EventRoundDTO: {
            /** Is Completed */
            is_completed: boolean;
            /** Is Published */
            is_published: boolean;
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
        };
        /**
         * EventSettingsDTO
         * @description Display / behaviour preferences resolved for an Event (Season).
         *
         *     Bag of flags rather than scattering each setting onto every DTO that
         *     needs them. Today a few items live on `League` (e.g. `show_fide_names`,
         *     `rating_type`); over time some may move to `Season`. Either way, the
         *     UI consumes them through this single object so callers don't need to
         *     track which model owns which flag.
         */
        EventSettingsDTO: {
            /** Use Fide Information */
            use_fide_information: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDTO */
        HealthDTO: {
            /** Ok */
            ok: boolean;
        };
        /**
         * MatchDTO
         * @description A single Match. In team Events this is a Player Match (one board of a
         *     Team Match); in lone Events it's a standalone Match.
         *
         *     ``*_username`` is the lichess handle (canonical identity, used for links
         *     to lichess.org/@/<handle>). ``*_fide_name`` is the player's FIDE name
         *     when known. ``*_rating`` is league-resolved (snapshot at game time when
         *     available, falling back to the player's current league rating).
         *     ``*_gender`` is the raw choice value (``male`` / ``female`` /
         *     ``non-binary`` / ``not-represented`` / ``prefer-not-disclose`` / ``""``).
         */
        MatchDTO: {
            /** Black Fide Name */
            black_fide_name: string | null;
            /** Black Gender */
            black_gender: string | null;
            /** Black Is Captain */
            black_is_captain: boolean;
            /** Black Rating */
            black_rating: number | null;
            /** Black Username */
            black_username: string | null;
            /** Board Number */
            board_number: number | null;
            /** Game Link */
            game_link: string;
            /** Id */
            id: number;
            /** Result */
            result: string;
            /** Team Match Id */
            team_match_id: number | null;
            /** White Fide Name */
            white_fide_name: string | null;
            /** White Gender */
            white_gender: string | null;
            /** White Is Captain */
            white_is_captain: boolean;
            /** White Rating */
            white_rating: number | null;
            /** White Username */
            white_username: string | null;
        };
        /**
         * MatchPresenceDTO
         * @description Presence pair — one entry per side of a single match. Keyed on the
         *     round-level map by `match.id` (= the PlayerPairing pk). `null` for a
         *     side means there's no player on that side (bye / unfilled board).
         */
        MatchPresenceDTO: {
            black: components["schemas"]["PlayerPresenceDTO"] | null;
            white: components["schemas"]["PlayerPresenceDTO"] | null;
        };
        /**
         * PlayerPresenceDTO
         * @description Presence info for one player on one match (board pairing).
         *
         *     `was_online` answers "did this player appear online during the round
         *     at all?" — the legacy template's "Online during round" header. The
         *     `events` list is ordered ascending by timestamp.
         */
        PlayerPresenceDTO: {
            /** Events */
            events: components["schemas"]["PresenceEventDTO"][];
            /** Plies Played */
            plies_played: number;
            /** Was Online */
            was_online: boolean;
        };
        /**
         * PresenceEventDTO
         * @description One entry in the staff-visible presence log next to a player.
         *
         *     Mirrors `PlayerPresenceEvent` (heltour/tournament/models.py:4374) — the
         *     same shape the legacy popover renders.
         */
        PresenceEventDTO: {
            /** Event Type */
            event_type: string;
            /** Event Type Display */
            event_type_display: string;
            /** Game Id */
            game_id: string | null;
            /** Timestamp */
            timestamp: string;
        };
        /** RoundMatchesDTO */
        RoundMatchesDTO: {
            /** Event Name */
            event_name: string;
            /** Event Tag */
            event_tag: string;
            /** Is Completed */
            is_completed: boolean;
            /** Is Team */
            is_team: boolean;
            /** League Tag */
            league_tag: string;
            /** Matches */
            matches: components["schemas"]["MatchDTO"][];
            /** Presence Events */
            presence_events: {
                [key: string]: components["schemas"]["MatchPresenceDTO"];
            };
            /** Round Id */
            round_id: number;
            /** Round Number */
            round_number: number;
            /** Rounds */
            rounds: components["schemas"]["EventRoundDTO"][];
            settings: components["schemas"]["EventSettingsDTO"];
            /** Team Matches */
            team_matches: components["schemas"]["TeamMatchDTO"][];
            viewer: components["schemas"]["ViewerDTO"];
        };
        /**
         * SetMatchResultRequest
         * @description Body of the staff-only `PUT /v1/matches/{id}/result` endpoint.
         *
         *     Empty string clears the result. Any other value must be one of
         *     ``RESULT_OPTIONS`` from `heltour/tournament/models.py:2409`; the route
         *     rejects anything else with a 422.
         */
        SetMatchResultRequest: {
            /** Result */
            result: string;
        };
        /**
         * TeamMatchDTO
         * @description A Team Match (Django ``TeamPairing``). Holds the two teams and the
         *     aggregated score; the actual board pairings (Player Matches) are in
         *     ``RoundMatchesDTO.matches`` linked via ``MatchDTO.team_match_id``.
         */
        TeamMatchDTO: {
            /** Black Score */
            black_score: number;
            /** Black Team Name */
            black_team_name: string | null;
            /** Black Team Number */
            black_team_number: number | null;
            /** Id */
            id: number;
            /** Is Bye */
            is_bye: boolean;
            /** Pairing Order */
            pairing_order: number;
            /** White Score */
            white_score: number;
            /** White Team Name */
            white_team_name: string;
            /** White Team Number */
            white_team_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ViewerDTO
         * @description Permission flags for the current request's viewer, scoped to one round.
         *
         *     A bag of booleans rather than a single role string so we can grow new
         *     surfaces (move history, tagging, etc.) without renumbering enum values.
         *     Today both flags are gated on the same Django permission
         *     (`tournament.change_pairing` against the league); we keep them
         *     separate so the UI doesn't have to know that.
         */
        ViewerDTO: {
            /** Can Edit Pairings */
            can_edit_pairings: boolean;
            /** Can View Presence Log */
            can_view_presence_log: boolean;
            /** Is Authenticated */
            is_authenticated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDTO"];
                };
            };
        };
    };
    current_round_v1_leagues__league_tag__current_round_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentRoundDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    round_matches_by_slug_v1_leagues__league_tag__events__event_tag__rounds__round_number__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_tag: string;
                event_tag: string;
                round_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundMatchesDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_match_result_v1_matches__match_id__result_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMatchResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDTO"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — viewer lacks change_pairing perm */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid result code */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    round_matches_by_id_v1_rounds__round_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundMatchesDTO"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
