http:
  routers:
    heltour:
      rule: Host(`www.lichess4545.com`) || Host(`lichess4545.com`)
      entryPoints: [websecure]
      service: heltour
      tls:
        certResolver: myresolver

  services:
    heltour:
      loadBalancer:
        servers:
          - url: https://legacy.heltour.internal
        serversTransport: legacy

  serversTransports:
    legacy:
      serverName: www.lichess4545.com
