# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoundChanges',
            new_name='RoundChange',
        ),
    ]
