# Generated by Django 4.2.20 on 2025-03-17 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_squashed_0195'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_validation_try',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
