# Generated by Django 4.2.20 on 2025-03-25 14:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_squashed_0195'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['is_completed', '-start_date'], 'permissions': (('generate_pairings', 'Can generate and review pairings'),)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('season__is_completed', '-season__start_date')},
        ),
    ]
