# Generated by Django 4.2.20 on 2025-03-25 14:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_squashed_0195'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['is_completed', 'league__name', '-name'], 'permissions': (('manage_players', 'Can manage players'), ('review_nominated_games', 'Can review nominated games'))},
        ),
    ]
