# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_auto_20160717_2019"),
    ]

    operations = [
        migrations.RenameField(
            model_name="round",
            old_name="round_number",
            new_name="number",
        ),
        migrations.AddField(
            model_name="pairing",
            name="black_team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairings_as_black",
                to="tournament.Team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pairing",
            name="white_team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairings_as_white",
                to="tournament.Team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="boards",
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammember",
            name="board_number",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5), ("6", 6)],
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set([("season", "number"), ("season", "name")]),
        ),
    ]
