# Generated by Django 4.2.20 on 2025-03-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_registration_last_validation_try'),
        ('tournament', '0002_round_team_ordering'),
        ('tournament', '0002_season_ordering'),
    ]

    operations = [
    ]
