# Generated by Django 2.2.28 on 2023-04-09 15:10

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_merge_20250331_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpairing',
            name='black_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpairing',
            name='white_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesetting',
            name='start_games',
            field=models.BooleanField(default=False, help_text='Try to start games automatically, if the scheduled time was confirmed by both players. Games are started in 5 minute batches.'),
        ),
        migrations.AddField(
            model_name='leaguesetting',
            name='start_clock_time',
            field=models.PositiveSmallIntegerField(default=6, help_text='For games started by us, start clocks n minutes later. Since we start games in 5 minute batches, a value of 5 will mean most games are started at the scheduled time. This also means that you should and cannot set this value below 5.', validators=[MinValueValidator(5, message='Values below 5 would make clocks start before the scheduled time.'), MaxValueValidator(30, message='Pick a value <= 30. If we start clocks too late, we might hit lichess api limits.')]),
        ),
        migrations.AddField(
            model_name='leaguesetting',
            name='start_clocks',
            field=models.BooleanField(default=False, help_text='For games started by us, automatically start clocks too.'),
        ),
        migrations.AlterField(
            model_name='playernotificationsetting',
            name='type',
            field=models.CharField(choices=[('round_started', 'Round started'), ('before_game_time', 'Before game time'), ('game_started', 'Game started'), ('game_time', 'Game time'), ('unscheduled_game', 'Unscheduled game'), ('game_warning', 'Game warning'), ('alternate_needed', 'Alternate needed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='playerpairing',
            name='tv_state',
            field=models.CharField(choices=[('default', 'Default'), ('hide', 'Hide'), ('has_moves', 'Has Moves')], default='default', max_length=31),
        ),
    ]
