# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20160718_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
