# Generated by Django 4.2.20 on 2025-05-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_playersetting_zen_mode'),
        ('tournament', '0006_league_channels'),
    ]

    operations = [
    ]
