# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:20


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0007_player_games_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
