# Generated by Django 4.2.21 on 2025-06-21 10:39
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0008_lichess_username_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playernotificationsetting",
            name="type",
            field=models.CharField(
                choices=[
                    ("round_started", "Round started"),
                    ("before_game_time", "Before game time"),
                    ("game_scheduled", "Game was scheduled"),
                    ("game_started", "Game started"),
                    ("game_time", "Game time"),
                    ("unscheduled_game", "Unscheduled game"),
                    ("game_warning", "Game warning"),
                    ("alternate_needed", "Alternate needed"),
                ],
                max_length=255,
            ),
        ),
    ]
