# Generated by Django 4.2.21 on 2025-07-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0009_alter_playernotificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpairing",
            name="broadcasted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="season",
            name="create_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("lichess_id", models.SlugField(blank=True, max_length=10)),
                ("lowest_board", models.PositiveSmallIntegerField(default=1)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "lowest_board"],
                "unique_together": {("season", "lowest_board")},
            },
        ),
        migrations.CreateModel(
            name="BroadcastRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("lichess_id", models.SlugField(blank=True, max_length=10)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.broadcast",
                    ),
                ),
                (
                    "round_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.round",
                    ),
                ),
            ],
            options={
                "ordering": ["broadcast", "round_id"],
                "unique_together": {("broadcast", "round_id")},
            },
        ),
    ]
