# Generated by Django 4.2.22 on 2025-07-13 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0009_alter_playernotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='registration_mode',
            field=models.CharField(choices=[('open', 'Open/Established Rating'), ('invite_only', 'Invite By Code')], default='open', help_text='Controls how players can register for this league', max_length=20),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this invite code')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='tournament.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='tournament.season')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite_codes', to='tournament.player')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='invite_code_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='tournament.invitecode'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['league', 'season', 'used_by'], name='tournament__league__8fef01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitecode',
            unique_together={('league', 'season', 'code')},
        ),
    ]
