# Generated by Django 4.2.22 on 2025-07-09 10:54

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0009_alter_playernotificationsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("lichess_id", models.SlugField(blank=True, max_length=10)),
                ("main_broadcast", models.BooleanField(default=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.season",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playerpairing",
            name="broadcasted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="season",
            name="create_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BroadcastRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("lichess_id", models.SlugField(blank=True, max_length=10)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.broadcast",
                    ),
                ),
                (
                    "round_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.round",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubBroadcast",
            fields=[
                (
                    "broadcast_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tournament.broadcast",
                    ),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subbroadcasts",
                        to="tournament.broadcast",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("tournament.broadcast",),
        ),
    ]
