# Generated by Django 4.2.22 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0009_alter_playernotificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguesetting",
            name="schedule_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Fixed Time - All games start at set times"),
                    (2, "Time Window - Players schedule within deadline"),
                ],
                default=1,
                help_text="How game scheduling is handled for this league",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="bulk_id",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
