# Generated by Django 4.2.22 on 2025-06-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_playernotificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_validation_try',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='validation_ok',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='validation_warning',
        ),
    ]
