# Generated by Django 4.2.22 on 2025-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_playernotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('teal', 'Teal'), ('pink', 'Pink'), ('brown', 'Brown')], max_length=32),
        ),
    ]
