# Generated by Django 4.2.22 on 2025-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0010_broadcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="broadcast_title_override",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
