# Generated by Django 4.2.21 on 2025-07-02 21:29

from django.db import migrations, models
import django.db.models.deletion


def create_player(apps, schema_editor):
    Player = apps.get_model("tournament", "Player")
    Registration = apps.get_model("tournament", "Registration")
    for reg in Registration.objects.all():
        player_name = reg.lichess_username
        if player_name:
            player, created = Player.objects.get_or_create(
                lichess_username__iexact=player_name,
                defaults={"lichess_username": player_name},
            )
            reg.player = player
            reg.save()


def reverse_lichess_username(apps, schema_editor):
    Registration = apps.get_model("tournament", "Registration")
    for reg in Registration.objects.all():
        reg.lichess_username = reg.player.lichess_username
        reg.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0010_remove_registration_last_validation_try_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.player",
            ),
        ),
        # add default to make reversible
        migrations.AlterField(
            model_name="registration",
            name="lichess_username",
            field=models.CharField(
                max_length=255,
                default="",
            ),
        ),
        migrations.RunPython(
            # no forward operation
            code=create_player,
            # backward operation to fetch the username from the player
            reverse_code=reverse_lichess_username,
        ),
    ]
