# Generated by Django 4.2.21 on 2025-07-08 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0011_registration_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="lichess_username",
        ),
    ]
