# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 20:03


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0012_auto_20160723_1942"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together=set([("lichess_username",)]),
        ),
    ]
