# Generated by Django 4.2.22 on 2025-08-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_starting_games'),
        ('tournament', '0013_broadcasts'),
    ]

    operations = [
    ]
