# Generated by Django 4.2.21 on 2025-08-09 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0013_broadcasts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={"ordering": ["season", "board_range_start"]},
        ),
        migrations.RenameField(
            model_name="broadcast",
            old_name="first_board",
            new_name="board_range_start",
        ),
        migrations.AlterUniqueTogether(
            name="broadcast",
            unique_together={("season", "board_range_start")},
        ),
    ]
