# Generated by Django 4.2.22 on 2025-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0010_league_registration_mode_invitecode_and_more"),
        ("tournament", "0014_merge_0010_starting_games_0013_broadcasts"),
    ]

    operations = []
