# Generated by Django 4.2.22 on 2025-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0017_captain_invite_code_management"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invitecode",
            new_name="tournament__created_db5094_idx",
            old_name="tournament_created_8e9c47_idx",
        ),
        migrations.AddField(
            model_name="leaguesetting",
            name="board_update_deadline_minutes",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Minutes before round start when team board assignments are locked",
            ),
        ),
    ]
