# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_registration_status_changed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='date_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
