# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20160724_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
