# Generated by Django 4.2.22 on 2025-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_optionally_ask_for_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='show_provisional_warning',
            field=models.BooleanField(default=True, help_text='If true, show warning about provisional ratings during registration. Default is true.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
