# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 18:59


from django.db import migrations
import heltour.tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_auto_20160724_1855'),
    ]

    operations = [
        migrations.RunSQL("CREATE UNIQUE INDEX lichess_username_idx ON tournament_player (LOWER(lichess_username));"),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([]),
        ),
    ]
