# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
