# Generated by Django 4.2.22 on 2025-09-07 17:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_remove_team_number_of_players_registration_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='country',
        ),
        migrations.AlterField(
            model_name='registration',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
