# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 03:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_auto_20160726_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
