# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:14


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_auto_20160726_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='league',
            name='tag',
            field=models.CharField(help_text='The league will be accessible at /{league_tag}/', max_length=31, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-_]*$', 'Only alphanumeric characters, hyphens, and underscores are allowed.')]),
        ),
        migrations.AlterField(
            model_name='leaguedocument',
            name='tag',
            field=models.CharField(help_text='The document will be accessible at /{league_tag}/document/{document_tag}/', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-_]*$', 'Only alphanumeric characters, hyphens, and underscores are allowed.')]),
        ),
        migrations.AlterField(
            model_name='leaguedocument',
            name='type',
            field=models.CharField(blank=True, choices=[('faq', 'FAQ'), ('rules', 'Rules'), ('intro', 'Intro')], max_length=255, null=True),
        ),
    ]
