# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_loneplayerpairing_teamplayerpairing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='teamplayerpairing',
            unique_together=set([('team_pairing', 'board_number')]),
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='board_number',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='team_pairing',
        ),
    ]
