# Generated by Django 4.2.22 on 2025-10-11 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_scorefield_quarter_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Announcement text. Supports rich text formatting.', verbose_name='Announcement Text')),
                ('status', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', help_text='Bootstrap alert style for the announcement', max_length=10, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, help_text='When this announcement should start showing. Leave empty to show immediately.', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When this announcement should stop showing. Leave empty to show indefinitely.', null=True, verbose_name='End Date')),
                ('path_prefix', models.CharField(default='/', help_text="Path prefix to show announcement on. '/' means all pages. '/tournament/' would show on tournament pages only.", max_length=255, verbose_name='Path Prefix')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is active', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-start_date'],
            },
        ),
    ]
