# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:21


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0031_auto_20160728_0520"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pairing",
            new_name="PlayerPairing",
        ),
    ]
