# Generated by Django 4.2.22 on 2025-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_scorefield_quarter_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='team_tiebreak_1',
            field=models.CharField(blank=True, choices=[('match_points', 'Match Points'), ('game_points', 'Game Points'), ('head_to_head', 'Head-to-Head'), ('games_won', 'Games Won'), ('sonneborn_berger', 'Sonneborn-Berger'), ('buchholz', 'Buchholz'), ('eggsb', 'EGGSB - Extended Game-Game Sonneborn-Berger'), ('emmsb', 'EMMSB - Extended Match-Match Sonneborn-Berger'), ('emgsb', 'EMGSB - Extended Match-Game Sonneborn-Berger'), ('egmsb', 'EGMSB - Extended Game-Match Sonneborn-Berger')], default='game_points', help_text='First tiebreak for team tournaments', max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='team_tiebreak_2',
            field=models.CharField(blank=True, choices=[('match_points', 'Match Points'), ('game_points', 'Game Points'), ('head_to_head', 'Head-to-Head'), ('games_won', 'Games Won'), ('sonneborn_berger', 'Sonneborn-Berger'), ('buchholz', 'Buchholz'), ('eggsb', 'EGGSB - Extended Game-Game Sonneborn-Berger'), ('emmsb', 'EMMSB - Extended Match-Match Sonneborn-Berger'), ('emgsb', 'EMGSB - Extended Match-Game Sonneborn-Berger'), ('egmsb', 'EGMSB - Extended Game-Match Sonneborn-Berger')], default='head_to_head', help_text='Second tiebreak for team tournaments', max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='team_tiebreak_3',
            field=models.CharField(blank=True, choices=[('match_points', 'Match Points'), ('game_points', 'Game Points'), ('head_to_head', 'Head-to-Head'), ('games_won', 'Games Won'), ('sonneborn_berger', 'Sonneborn-Berger'), ('buchholz', 'Buchholz'), ('eggsb', 'EGGSB - Extended Game-Game Sonneborn-Berger'), ('emmsb', 'EMMSB - Extended Match-Match Sonneborn-Berger'), ('emgsb', 'EMGSB - Extended Match-Game Sonneborn-Berger'), ('egmsb', 'EGMSB - Extended Game-Match Sonneborn-Berger')], default='games_won', help_text='Third tiebreak for team tournaments', max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='team_tiebreak_4',
            field=models.CharField(blank=True, choices=[('match_points', 'Match Points'), ('game_points', 'Game Points'), ('head_to_head', 'Head-to-Head'), ('games_won', 'Games Won'), ('sonneborn_berger', 'Sonneborn-Berger'), ('buchholz', 'Buchholz'), ('eggsb', 'EGGSB - Extended Game-Game Sonneborn-Berger'), ('emmsb', 'EMMSB - Extended Match-Match Sonneborn-Berger'), ('emgsb', 'EMGSB - Extended Match-Game Sonneborn-Berger'), ('egmsb', 'EGMSB - Extended Game-Match Sonneborn-Berger')], default='sonneborn_berger', help_text='Fourth tiebreak for team tournaments', max_length=32),
        ),
    ]
