# Generated by Django 4.2.22 on 2025-10-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_alter_league_team_tiebreak_1_and_more'),
        ('tournament', '0032_announcement'),
    ]

    operations = [
    ]
