# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_auto_20160728_0612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamscore',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.Team'),
        ),
    ]
