# Generated by Django 4.2.22 on 2025-10-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_knockoutbracket_league_knockout_games_per_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutbracket',
            name='matches_per_stage',
            field=models.PositiveIntegerField(default=1, help_text='Number of matches each team pair plays per stage (1=single elimination, 2=return matches, etc.)'),
        ),
        migrations.CreateModel(
            name='TeamMultiMatchProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField(help_text='Round number in knockout bracket')),
                ('stage_name', models.CharField(help_text="Stage name (e.g., 'semifinals', 'finals')", max_length=32)),
                ('original_pairing_order', models.PositiveIntegerField(help_text='Original pairing order within the stage (1, 2, 3, 4, ...)')),
                ('matches_completed', models.PositiveIntegerField(default=0, help_text='Number of matches completed by this team pair')),
                ('total_matches_required', models.PositiveIntegerField(help_text='Total matches this team pair must complete before elimination')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.knockoutbracket')),
                ('opponent_team', models.ForeignKey(help_text='The team this team is paired against', on_delete=django.db.models.deletion.CASCADE, related_name='multi_match_opponent_progress', to='tournament.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
            options={
                'indexes': [models.Index(fields=['bracket', 'round_number', 'original_pairing_order'], name='tournament__bracket_8cd711_idx'), models.Index(fields=['bracket', 'round_number', 'matches_completed'], name='tournament__bracket_bb09ff_idx')],
                'unique_together': {('bracket', 'team', 'round_number')},
            },
        ),
    ]
