# Generated by Django 4.2.22 on 2025-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_knockoutbracket_matches_per_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='regional_rating_name',
            field=models.CharField(blank=True, default='', help_text="Name of the regional rating system (e.g., 'USCF', 'ECF', 'CFC'). Used when require_regional_rating is True.", max_length=100),
        ),
        migrations.AddField(
            model_name='league',
            name='require_contact_number',
            field=models.BooleanField(default=False, help_text='If true, require contact_number during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_corporate_email',
            field=models.BooleanField(default=False, help_text='If true, require corporate_email during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_date_of_birth',
            field=models.BooleanField(default=False, help_text='If true, require date_of_birth during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_fide_id',
            field=models.BooleanField(default=False, help_text='If true, require FIDE ID during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_gender',
            field=models.BooleanField(default=False, help_text='If true, require gender during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_name',
            field=models.BooleanField(default=False, help_text='If true, require first_name and last_name during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_nationality',
            field=models.BooleanField(default=False, help_text='If true, require nationality during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_personal_email',
            field=models.BooleanField(default=False, help_text='If true, require personal_email during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='league',
            name='require_regional_rating',
            field=models.BooleanField(default=False, help_text='If true, require a regional rating during registration. Default is false.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='regional_rating',
            field=models.CharField(blank=True, max_length=20, verbose_name='Regional Rating'),
        ),
    ]
