# Generated by Django 4.2.22 on 2025-11-10 14:10

from django.db import migrations


def set_existing_leagues_to_require_fields(apps, schema_editor):
    """
    Set granular field requirements to True for all existing leagues.
    This maintains backward compatibility with the previous hardcoded behavior where
    personal and corporate info fields were always required.

    This migration replaces the old bundled settings:
    - require_personal_info=True (which included: first_name, last_name, gender, date_of_birth, nationality)
    - require_corporate_info=True (which included: corporate_email, personal_email, contact_number)

    With the new granular settings that allow each field to be controlled individually.

    New leagues created after this migration will have these fields default to False,
    giving tournament organizers the flexibility to choose which fields to require.
    """
    League = apps.get_model('tournament', 'League')

    # Update all existing leagues to require the standard set of fields
    # This mimics the old require_personal_info=True and require_corporate_info=True behavior
    League.objects.all().update(
        require_name=True,              # Was part of require_personal_info
        require_personal_email=True,    # Was part of require_corporate_info
        require_gender=True,            # Was part of require_personal_info
        require_date_of_birth=True,     # Was part of require_personal_info
        require_nationality=True,       # Was part of require_personal_info
        require_corporate_email=True,   # Was part of require_corporate_info
        require_contact_number=True,    # Was part of require_corporate_info
        # require_fide_id remains False (was optional before, stays optional)
        # require_regional_rating is new, defaults to False
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by setting all leagues back to the new defaults (False).
    """
    League = apps.get_model('tournament', 'League')

    League.objects.all().update(
        require_name=False,
        require_personal_email=False,
        require_gender=False,
        require_date_of_birth=False,
        require_nationality=False,
        require_corporate_email=False,
        require_contact_number=False,
        require_fide_id=False,
        require_regional_rating=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0036_league_regional_rating_name_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_leagues_to_require_fields, reverse_migration),
    ]
