# Generated by Django 4.2.22 on 2026-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_league_lone_tiebreak_1_league_lone_tiebreak_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fide_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='fide_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='rating_type',
            field=models.CharField(choices=[('classical', 'Classical'), ('rapid', 'Rapid'), ('chess960', 'Chess 960'), ('blitz', 'Blitz'), ('fide_standard', 'FIDE Standard'), ('fide_rapid', 'FIDE Rapid'), ('fide_blitz', 'FIDE Blitz')], max_length=32),
        ),
    ]
