# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_auto_20160729_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='publish_pairings',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('''UPDATE tournament_round SET publish_pairings=TRUE'''),
    ]
