# Generated by Django 4.2.22 on 2026-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0039_player_fide_id_player_fide_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='show_fide_names',
            field=models.BooleanField(default=False, help_text='If true, display FIDE names with lichess usernames in parentheses.'),
        ),
    ]
