# Generated by Django 4.2.22 on 2026-02-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0039_league_skip_slack_invites'),
        ('tournament', '0040_league_show_fide_names'),
    ]

    operations = [
    ]
