# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0040_auto_20160801_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscore',
            name='game_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='match_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
