# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_auto_20160801_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set([('team', 'board_number')]),
        ),
    ]
