# Generated by Django 4.2.22 on 2026-03-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_season_predefined_player_list_season_validation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='validate_account_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_agreed_to_rules',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_agreed_to_tos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_has_rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_not_provisional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_predefined_list',
            field=models.BooleanField(default=False),
        ),
    ]
