# Generated by Django 4.2.22 on 2026-03-05 00:59

from django.db import migrations


def forward(apps, schema_editor):
    Season = apps.get_model("tournament", "Season")
    for season in Season.objects.filter(validation_mode="predefined_list"):
        season.validate_predefined_list = True
        season.validate_account_status = True
        season.validate_has_rating = False
        season.validate_not_provisional = False
        season.validate_agreed_to_rules = True
        season.validate_agreed_to_tos = True
        season.save()


def backward(apps, schema_editor):
    Season = apps.get_model("tournament", "Season")
    for season in Season.objects.filter(validate_predefined_list=True):
        season.validation_mode = "predefined_list"
        season.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0043_season_validate_account_status_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
