# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:05


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0044_auto_20160802_0342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
