# Generated by Django 4.2.22 on 2026-03-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0044_port_validation_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='validation_mode',
        ),
    ]
