# Generated by Django 4.2.22 on 2026-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0046_registration_validation_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='validate_predefined_list',
            new_name='validate_predefined_list_contains_username_fide_id_together',
        ),
        migrations.AddField(
            model_name='season',
            name='validate_predefined_list_contains_username',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='validate_predefined_list_contains_fide_id',
            field=models.BooleanField(default=False),
        ),
    ]
