# Generated by Django 4.2.22 on 2026-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournament",
            "0047_rename_validate_predefined_list_season_validate_predefined_list_fide_id_matches_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="organisation_label",
            field=models.CharField(
                blank=True,
                default="Company / University / Organisation",
                help_text="Label used for organisation-related fields in registration and team creation forms (e.g., 'Company', 'University', 'Organisation').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="company_address",
            field=models.TextField(blank=True, verbose_name="Physical address"),
        ),
        migrations.AlterField(
            model_name="team",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Organisation name"),
        ),
    ]
