# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0047_auto_20160802_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpairing',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_black', to='tournament.Player'),
        ),
        migrations.AlterField(
            model_name='playerpairing',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_white', to='tournament.Player'),
        ),
    ]
