# Generated by Django 4.2.22 on 2026-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournament",
            "0048_league_organisation_label_alter_team_company_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="theme",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("custom", "Custom (colors from settings)"),
                ],
                max_length=32,
            ),
        ),
    ]
