# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 05:22


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0049_auto_20160804_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternate',
            name='player',
        ),
        migrations.RemoveField(
            model_name='alternate',
            name='season',
        ),
        migrations.AlterField(
            model_name='alternate',
            name='season_player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.SeasonPlayer'),
        ),
    ]
