# Generated by Django 4.2.22 on 2026-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0049_alter_league_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                    ("not-represented", "My gender is not represented"),
                    ("prefer-not-disclose", "Prefer not to disclose"),
                ],
                max_length=50,
            ),
        ),
    ]
