# Generated by Django 4.2.22 on 2026-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0050_player_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="rating_type",
            field=models.CharField(
                choices=[
                    ("classical", "Classical"),
                    ("rapid", "Rapid"),
                    ("chess960", "Chess 960"),
                    ("blitz", "Blitz"),
                    ("fide_standard", "FIDE Standard"),
                    ("fide_rapid", "FIDE Rapid"),
                    ("fide_blitz", "FIDE Blitz"),
                    ("fide", "FIDE (Standard → Rapid → Blitz)"),
                ],
                max_length=32,
            ),
        ),
    ]
