# Generated by Django 4.2.22 on 2026-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0051_alter_league_rating_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="team_tiebreak_5",
            field=models.CharField(
                blank=True,
                choices=[
                    ("match_points", "Match Points"),
                    ("game_points", "Game Points"),
                    ("head_to_head", "Head-to-Head"),
                    ("games_won", "Games Won"),
                    ("sonneborn_berger", "Sonneborn-Berger"),
                    ("buchholz", "Buchholz"),
                    ("eggsb", "EGGSB - Extended Game-Game Sonneborn-Berger"),
                    ("emmsb", "EMMSB - Extended Match-Match Sonneborn-Berger"),
                    ("emgsb", "EMGSB - Extended Match-Game Sonneborn-Berger"),
                    ("egmsb", "EGMSB - Extended Game-Match Sonneborn-Berger"),
                ],
                default="",
                help_text="Fifth tiebreak for team tournaments",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="team_tiebreak_6",
            field=models.CharField(
                blank=True,
                choices=[
                    ("match_points", "Match Points"),
                    ("game_points", "Game Points"),
                    ("head_to_head", "Head-to-Head"),
                    ("games_won", "Games Won"),
                    ("sonneborn_berger", "Sonneborn-Berger"),
                    ("buchholz", "Buchholz"),
                    ("eggsb", "EGGSB - Extended Game-Game Sonneborn-Berger"),
                    ("emmsb", "EMMSB - Extended Match-Match Sonneborn-Berger"),
                    ("emgsb", "EMGSB - Extended Match-Game Sonneborn-Berger"),
                    ("egmsb", "EGMSB - Extended Game-Match Sonneborn-Berger"),
                ],
                default="",
                help_text="Sixth tiebreak for team tournaments",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="team_tiebreak_7",
            field=models.CharField(
                blank=True,
                choices=[
                    ("match_points", "Match Points"),
                    ("game_points", "Game Points"),
                    ("head_to_head", "Head-to-Head"),
                    ("games_won", "Games Won"),
                    ("sonneborn_berger", "Sonneborn-Berger"),
                    ("buchholz", "Buchholz"),
                    ("eggsb", "EGGSB - Extended Game-Game Sonneborn-Berger"),
                    ("emmsb", "EMMSB - Extended Match-Match Sonneborn-Berger"),
                    ("emgsb", "EMGSB - Extended Match-Game Sonneborn-Berger"),
                    ("egmsb", "EGMSB - Extended Game-Match Sonneborn-Berger"),
                ],
                default="",
                help_text="Seventh tiebreak for team tournaments",
                max_length=32,
            ),
        ),
    ]
