# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0051_playeravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playeravailability',
            options={'verbose_name_plural': 'player availabilities'},
        ),
        migrations.AddField(
            model_name='seasonplayer',
            name='unresponsive',
            field=models.BooleanField(default=False),
        ),
    ]
