# Generated by Django 4.2.22 on 2026-05-02 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0052_league_team_tiebreak_5_league_team_tiebreak_6_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpairing",
            name="plies_played",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PlayerPresenceEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("online", "online"),
                            ("offline", "offline"),
                            ("playing_started", "playing started"),
                            ("playing_ended", "playing ended"),
                            ("first_chat_message", "first chat message"),
                        ],
                        max_length=32,
                    ),
                ),
                ("game_id", models.CharField(blank=True, max_length=32)),
                (
                    "pairing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournament.playerpairing",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tournament.round",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["player", "timestamp"],
                        name="tournament__player__2edef2_idx",
                    ),
                    models.Index(
                        fields=["pairing", "timestamp"],
                        name="tournament__pairing_348d2b_idx",
                    ),
                    models.Index(
                        fields=["round", "timestamp"],
                        name="tournament__round_i_839c5c_idx",
                    ),
                ],
            },
        ),
    ]
