# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0052_auto_20160805_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='seed_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
