# Generated by Django 4.2.22 on 2026-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0053_playerpairing_plies_played_playerpresenceevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="knockoutbracket",
            name="match_generation",
            field=models.CharField(
                choices=[
                    (
                        "lockstep",
                        "Lockstep (next match created only after every bracket finishes the current one)",
                    ),
                    (
                        "upfront",
                        "Up-front (all matches of a stage created at once, so each bracket can play back-to-back)",
                    ),
                ],
                default="lockstep",
                help_text="How multi-match stages are generated. 'lockstep' creates the next match only once every bracket has finished the current one (use when litour runs the whole event). 'upfront' creates all of a stage's matches at once so each bracket can play its matches back-to-back independently (use when an external tool runs games).",
                max_length=16,
            ),
        ),
    ]
