# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0053_team_seed_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedocument',
            name='type',
            field=models.CharField(blank=True, choices=[('faq', 'FAQ'), ('rules', 'Rules'), ('intro', 'Intro'), ('slack-welcome', 'Slack Welcome')], max_length=255),
        ),
    ]
