# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0054_auto_20160808_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='moderator_notes',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='moderator_notes',
        ),
    ]
