# Generated by Django 4.2.22 on 2026-05-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0054_knockoutbracket_match_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="knockoutseeding",
            name="seed_label",
            field=models.CharField(
                blank=True,
                help_text="Optional display label that overrides the numeric seed in the bracket (e.g. 'OSQ1 #1')",
                max_length=64,
            ),
        ),
    ]
