# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0056_auto_20160810_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tag',
            field=models.SlugField(help_text='The league will be accessible at /{league_tag}/', unique=True),
        ),
        migrations.AlterField(
            model_name='leaguedocument',
            name='tag',
            field=models.SlugField(help_text='The document will be accessible at /{league_tag}/document/{document_tag}/'),
        )
    ]
