# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0062_auto_20160814_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='tag',
            field=models.SlugField(default='4', help_text='The season will be accessible at /{league_tag}/season/{season_tag}/'),
            preserve_default=False,
        ),
    ]
