# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0064_auto_20160814_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonePlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('late_join_points', models.PositiveIntegerField(default=0)),
                ('tiebreak1', models.PositiveIntegerField(default=0)),
                ('tiebreak2', models.PositiveIntegerField(default=0)),
                ('tiebreak3', models.PositiveIntegerField(default=0)),
                ('tiebreak4', models.PositiveIntegerField(default=0)),
                ('season_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.SeasonPlayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roundchange',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tournament.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='boards',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
