# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:05


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0071_auto_20160817_2044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundchange",
            name="player",
        ),
        migrations.RemoveField(
            model_name="roundchange",
            name="round",
        ),
        migrations.DeleteModel(
            name="RoundChange",
        ),
    ]
