# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0072_auto_20160817_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LateRegisterRoundChange',
            new_name='PlayerLateRegistration',
        ),
        migrations.RenameModel(
            old_name='WithdrawRoundChange',
            new_name='PlayerWithdrawl',
        ),
    ]
