# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0073_auto_20160817_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbye',
            name='type',
            field=models.CharField(choices=[('full-point-pairing-bye', 'Full-Point Bye (Pairing)'), ('full-point-bye', 'Full-Point Bye'), ('half-point-bye', 'Half-Point Bye'), ('zero-point-bye', 'Zero-Point Bye')], max_length=31),
        ),
    ]
