# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 04:30


from django.db import migrations
import heltour.tournament.models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0076_auto_20160818_2336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerlateregistration",
            name="late_join_points",
            field=heltour.tournament.models.ScoreField(default=0),
        ),
    ]
