# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 01:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import heltour.tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0081_auto_20160829_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateUrlAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('authenticated_user', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w-]+$')])),
                ('secret_token', models.CharField(default=heltour.tournament.models.create_api_token, max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
