# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0083_auto_20160901_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenomination',
            name='pairing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.PlayerPairing'),
        ),
    ]
