# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 19:21


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0087_season_nominations_open"),
        ("tournament", "0087_navitem"),
    ]

    operations = []
