# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0088_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
