# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0090_auto_20160912_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_moderator',
        ),
    ]
