# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0091_remove_player_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemoderator',
            name='send_contact_emails',
            field=models.BooleanField(default=True),
        ),
    ]
