# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:48


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0092_leaguemoderator_send_contact_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpairing",
            name="colors_reversed",
            field=models.BooleanField(default=False),
        ),
    ]
