# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0093_playerpairing_colors_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playoffs',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Quarter-Finals'), (2, 'Semi-Finals'), (3, 'Finals')], default=0),
        ),
    ]
