# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 23:05


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0094_season_playoffs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="playoffs",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Finals"),
                    (2, "Semi-Finals"),
                    (3, "Quarter-Finals"),
                ],
                default=0,
            ),
        ),
    ]
