# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0095_auto_20160914_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscore',
            name='playoff_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
