# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0096_teamscore_playoff_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpairing',
            name='tv_state',
            field=models.CharField(choices=[('default', 'Default'), ('hide', 'Hide')], default='default', max_length=31),
        ),
    ]
