# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 19:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0097_playerpairing_tv_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_slack_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lichess_username',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\w-]+$')]),
        ),
    ]
