# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 01:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0098_auto_20160916_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate',
            name='priority_date_override',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
