# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0101_alternateassignment_replaced_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpairing',
            name='black_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerpairing',
            name='white_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
