# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0102_auto_20161008_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbye',
            name='player_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
