# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0103_playerbye_player_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate',
            name='player_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='player_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
