# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:59


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0104_auto_20161008_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonplayer",
            name="final_rating",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
