# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 05:46


from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0105_seasonplayer_final_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternateassignment",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="availabletime",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="gamenomination",
            name="nominating_player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="leaguemoderator",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="playeravailability",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="playerbye",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="playerlateregistration",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="playerwithdrawl",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="seasonplayer",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="seasonprizewinner",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="player",
            field=select2.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Player"
            ),
        ),
    ]
