# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 21:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0106_auto_20161031_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateassignment',
            name='replaced_player',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_replacements', to='tournament.Player'),
        ),
        migrations.AlterField(
            model_name='playerpairing',
            name='black',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_black', to='tournament.Player'),
        ),
        migrations.AlterField(
            model_name='playerpairing',
            name='white',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_white', to='tournament.Player'),
        ),
    ]
