# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 23:41


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0107_auto_20161101_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="time_control",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
