# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 04:40


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0110_scheduledevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("notify_mods_unscheduled", "Notify mods of unscheduled games"),
                    ("notify_mods_no_result", "Notify mods of games without results"),
                ],
                max_length=255,
            ),
        ),
    ]
