# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 04:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0112_auto_20161127_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('unresponsive', 'Unresponsive')], max_length=31),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='alternate_status',
            field=models.CharField(blank=True, choices=[('search_started', 'Search started'), ('all_contacted', 'All alternates contacted')], max_length=31),
        ),
        migrations.AddField(
            model_name='season',
            name='enable_alternates_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaguenotification',
            name='type',
            field=models.CharField(choices=[('mod', 'Moderation stream'), ('captains', 'Captains stream')], max_length=255),
        ),
    ]
