# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 00:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0115_auto_20161216_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('round_started', 'Round started'), ('before_game_time', 'Before game time'), ('game_time', 'Game time'), ('unscheduled_game', 'Unscheduled game'), ('game_warning', 'Game warning')], max_length=255)),
                ('offset', models.DurationField(blank=True, null=True)),
                ('enable_lichess_mail', models.BooleanField()),
                ('enable_slack_im', models.BooleanField()),
                ('enable_slack_mpim', models.BooleanField()),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.League')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='leaguenotification',
            name='type',
            field=models.CharField(choices=[('mod', 'Moderation stream'), ('captains', 'Captains stream'), ('scheduling', 'Scheduling')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='relative_to',
            field=models.CharField(choices=[('round_start', 'Round start'), ('round_end', 'Round end'), ('game_scheduled_time', 'Game scheduled time')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='type',
            field=models.CharField(choices=[('notify_mods_unscheduled', 'Notify mods of unscheduled games'), ('notify_mods_no_result', 'Notify mods of games without results'), ('start_round_transition', 'Start round transition'), ('notify_players_round_start', 'Notify players of the round start'), ('notify_players_unscheduled', 'Notify players of unscheduled games'), ('notify_players_game_time', 'Notify players of their game time')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='playernotificationsetting',
            unique_together=set([('player', 'type', 'offset')]),
        ),
    ]
