# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0117_auto_20161219_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguenotification',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaguenotification',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='playernotificationsetting',
            unique_together=set([('player', 'type', 'league')]),
        ),
    ]
