# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0119_auto_20161220_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguechannel',
            name='type',
            field=models.CharField(choices=[('mod', 'Mods'), ('captains', 'Captains'), ('scheduling', 'Scheduling')], max_length=255),
        ),
    ]
