# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 01:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0120_auto_20161220_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguechannel',
            old_name='enabled',
            new_name='send_messages',
        ),
    ]
