# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0122_auto_20161221_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username_exists',
            field=models.NullBooleanField(default=None),
        ),
    ]
