# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 23:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0123_registration_username_exists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='username_exists',
            new_name='validation_ok',
        ),
    ]
