# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 00:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0124_auto_20161228_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='account_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('engine', 'Engine'), ('booster', 'Booster')], default='normal', max_length=31),
        ),
    ]
