# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0125_player_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
