# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0127_auto_20161230_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('unresponsive', 'Unresponsive')], default='waiting', max_length=31),
        ),
    ]
