# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0129_auto_20161231_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatesearch',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('all_contacted', 'All alternates contacted'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=31),
        ),
    ]
