# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-31 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0130_auto_20161231_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='validation_warning',
            field=models.BooleanField(default=False),
        ),
    ]
