# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0132_auto_20170103_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatesearch',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('all_contacted', 'All alternates contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=31),
        ),
    ]
