# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0133_auto_20170103_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red')], max_length=32),
        ),
    ]
