# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0134_auto_20170108_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='round_duration',
            field=models.DurationField(default=datetime.timedelta(7)),
        ),
    ]
