# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 21:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0135_season_round_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='rating_type',
            field=models.CharField(choices=[('classical', 'Classical'), ('blitz', 'Blitz')], default='classical', max_length=32),
            preserve_default=False,
        ),
    ]
