# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 22:23


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0136_league_rating_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="alternate_preference",
            field=models.CharField(
                blank=True,
                choices=[("alternate", "Alternate"), ("full_time", "Full Time")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="previous_season_alternate",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "alternate",
                        "Yes, I was an alternate at the end of the last season.",
                    ),
                    (
                        "alternate_to_full_time",
                        "Yes, but I was able to find a consistent team (did not simply fill in for a week or two).",
                    ),
                    (
                        "full_time",
                        "No, I was not an alternate for the last season. I played the season.",
                    ),
                    (
                        "new",
                        "No, I was not an alternate for the last season. I am a new member / I took last season off.",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
