# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0137_auto_20170108_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemoderator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
