# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 02:16


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0138_player_profile"),
        ("tournament", "0138_leaguemoderator_is_active"),
    ]

    operations = []
