# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 17:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0139_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguedocument",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Document"
            ),
        ),
        migrations.AlterField(
            model_name="seasondocument",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.Document"
            ),
        ),
    ]
