# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 00:40


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0140_auto_20170122_1710"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="league",
            options={"permissions": (("view_dashboard", "Can view dashboard"),)},
        ),
    ]
