# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 20:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0142_auto_20170124_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lichess_username'], 'permissions': (('invite_to_slack', 'Can invite to slack'),)},
        ),
    ]
