# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 18:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0144_league_enable_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='type',
            field=models.CharField(choices=[('notify_mods_unscheduled', 'Notify mods of unscheduled games'), ('notify_mods_no_result', 'Notify mods of games without results'), ('notify_mods_pending_regs', 'Notify mods of pending registrations'), ('start_round_transition', 'Start round transition'), ('notify_players_unscheduled', 'Notify players of unscheduled games'), ('notify_players_game_time', 'Notify players of their game time')], max_length=255),
        ),
    ]
