# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0147_auto_20170223_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='timezone_offset',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
