# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-03 02:54


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0153_leaguesetting_max_game_nominations_per_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="FcmSub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("slack_user_id", models.CharField(max_length=31)),
                ("reg_id", models.CharField(max_length=4096, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
