# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0154_fcmsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatesmanagersetting',
            name='rating_flex',
            field=models.PositiveIntegerField(default=0, help_text="How far out of a board's rating range an alternate can be if it helps alternate balance."),
        ),
    ]
