# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 23:19


from django.db import migrations, models
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0155_alternatesmanagersetting_rating_flex"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("withdraw", "Withdraw"),
                            ("reregister", "Re-register"),
                            ("appeal_late_response", "Appeal late response"),
                            ("claim_win_noshow", "Claim a forfeit win (no-show)"),
                            (
                                "claim_win_effort",
                                "Claim a forfeit win (insufficient effort)",
                            ),
                            ("claim_draw_scheduling", "Claim a scheduling draw"),
                            ("claim_loss", "Claim a forfeit loss"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=31,
                    ),
                ),
                ("status_changed_by", models.CharField(blank=True, max_length=255)),
                ("status_changed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="screenshots/%Y/%m/%d/"
                    ),
                ),
                ("response", models.TextField(blank=True)),
                (
                    "pairing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.PlayerPairing",
                    ),
                ),
                (
                    "requester",
                    select2.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Round",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.Season",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
