# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 01:33


from django.db import migrations, models
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0157_playerpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('unresponsive', 'Unresponsive')], max_length=255)),
                ('player', select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Player')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='modrequest',
            name='type',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('reregister', 'Re-register'), ('appeal_late_response', 'Appeal late response'), ('claim_win_noshow', 'Claim a forfeit win (no-show)'), ('claim_win_effort', 'Claim a forfeit win (insufficient effort)'), ('claim_draw_scheduling', 'Claim a scheduling draw'), ('claim_loss', 'Claim a forfeit loss'), ('request_continuation', 'Request continuation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='type',
            field=models.CharField(choices=[('notify_mods_unscheduled', 'Notify mods of unscheduled games'), ('notify_mods_no_result', 'Notify mods of games without results'), ('notify_mods_pending_regs', 'Notify mods of pending registrations'), ('start_round_transition', 'Start round transition'), ('notify_players_unscheduled', 'Notify players of unscheduled games'), ('notify_players_game_time', 'Notify players of their game time'), ('automod_unresponsive', 'Auto-mod unresponsive players')], max_length=255),
        ),
    ]
