# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-18 03:29


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0160_auto_20170918_0025"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintoken",
            name="username_hint",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
