# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-20 22:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0162_auto_20170920_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackaccount',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='in_slack_group',
        ),
        migrations.AddField(
            model_name='player',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='SlackAccount',
        ),
    ]
