# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0163_auto_20170920_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='mail_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
