# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-28 19:48


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0167_auto_20171025_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='section_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tournament.SectionGroup'),
            preserve_default=False,
        ),
    ]
