# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-28 20:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0168_auto_20171028_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='section_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Section'),
        ),
    ]
