# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-31 20:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0175_auto_20180117_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
