# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-07 11:30


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0176_logintoken_source_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="avoid",
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
