# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-10 03:01


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0178_auto_20180213_0442"),
        ("tournament", "0177_registration_avoid"),
    ]

    operations = []
