# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-10 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0179_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesetting',
            name='contact_period',
            field=models.DurationField(default=datetime.timedelta(2)),
        ),
    ]
