# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-28 23:44


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0181_auto_20180610_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("withdraw", "Withdraw"),
                    ("reregister", "Re-register"),
                    ("appeal_late_response", "Appeal late response"),
                    ("appeal_noshow", "Appeal no-show"),
                    ("appeal_draw_scheduling", "Appeal scheduling draw"),
                    ("claim_win_noshow", "Claim a forfeit win (no-show)"),
                    ("claim_win_effort", "Claim a forfeit win (insufficient effort)"),
                    ("claim_draw_scheduling", "Claim a scheduling draw"),
                    ("claim_loss", "Claim a forfeit loss"),
                    ("request_continuation", "Request continuation"),
                ],
                max_length=255,
            ),
        ),
    ]
