# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0182_auto_20180728_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='rating_type',
            field=models.CharField(choices=[('classical', 'Classical'),
                                            ('rapid', 'Rapid'),
                                            ('chess960', 'Chess 960'),
                                            ('blitz', 'Blitz'),
                                            ('crazyhouse', 'Crazyhouse')],
                                   max_length=32),
        ),
    ]
