# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0183_auto_20190214_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='games_per_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
