# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-12 01:17
from __future__ import unicode_literals

from django.db import migrations

def assign_user_to_player_and_registration(apps, schema_editor):
    # This can be done in a single query but I can't figure out the
    # ORM way so I'll just do it in python. This is super inefficient.

    Player = apps.get_model('tournament', 'Player')
    Registration = apps.get_model('tournament', 'Registration')
    User = apps.get_model('auth', 'User')

    users = User.objects.all()

    def join(objects):
        for o in objects:
            for user in users:
                if o.lichess_username.lower() == user.username.lower():
                    o.user = user
                    o.save()
                    break

    join(Player.objects.all())
    join(Registration.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0184_auto_20190512_0116'),
    ]

    operations = [
        migrations.RunPython(assign_user_to_player_and_registration),
    ]
