# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-22 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0185_auto_20191221_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
