# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0185_auto_20190306_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayerpairing',
            name='black_player_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player_pairings', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='teamplayerpairing',
            name='white_player_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player_pairings', to='tournament.Team'),
        ),
    ]
