# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0184_auto_20190518_1606'),
        ('tournament', '0185_auto_20190512_0117'),
    ]

    operations = [
    ]
