# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0187_auto_20190410_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesetting',
            name='friends_and_avoids',
            field=models.BooleanField(default=True),
        ),
    ]
