# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0187_auto_20190518_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['user__username'], 'permissions': (('change_player_details', 'Can change player details'), ('invite_to_slack', 'Can invite to slack'), ('link_slack', 'Can manually link slack accounts'))},
        ),
        migrations.RemoveField(
            model_name='player',
            name='lichess_username',
        ),
    ]
