# Generated by Django 2.2.13 on 2021-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0188_auto_20191223_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternate",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="alternateassignment",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="alternatebucket",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="alternatesearch",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="teamplayerpairing",
            name="board_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                ]
            ),
        ),
    ]
