# Generated by Django 2.2.13 on 2021-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0189_auto_20210221_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gdpr_erased',
            field=models.BooleanField(default=False),
        ),
    ]
