# Generated by Django 2.2.13 on 2021-10-08 05:40

from django.db import migrations


class Migration(migrations.Migration):
    def update_round_start_mpim(apps, schema_editor):
        PlayerNotificationSettings = apps.get_model(
            "tournament", "PlayerNotificationSetting"
        )
        PlayerNotificationSettings.objects.filter(
            type="round_started", enable_slack_mpim=False
        ).update(enable_slack_mpim=True)

    dependencies = [
        ("tournament", "0192_player_account_status"),
    ]

    operations = [
        migrations.RunPython(
            update_round_start_mpim, reverse_code=migrations.RunPython.noop
        ),
    ]
