# Generated by Django 2.2.27 on 2022-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0193_enable_round_start_mpim"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpairing",
            name="date_player_changed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
