# Generated by Django 2.2.28 between 2023-03-12 17:28 and 2023-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0194_playerpairing_last_time_player_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='classical_rating',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='peak_classical_rating',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='already_in_slack_group',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='previous_season_alternate',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='slack_username',
        ),
    ]
