# Generated by Django 2.2.28 on 2023-03-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0195_auto_20230312_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='already_in_slack_group',
        ),
    ]
