# Generated by Django 2.2.28 on 2023-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0194_playerpairing_last_time_player_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpairing',
            name='black_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerpairing',
            name='white_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesetting',
            name='start_games',
            field=models.BooleanField(default=False, help_text='Try to start games automatically, if the scheduled time was confirmed by both players'),
        ),
        migrations.AlterField(
            model_name='playernotificationsetting',
            name='type',
            field=models.CharField(choices=[('round_started', 'Round started'), ('before_game_time', 'Before game time'), ('game_started', 'Game started'), ('game_time', 'Game time'), ('unscheduled_game', 'Unscheduled game'), ('game_warning', 'Game warning'), ('alternate_needed', 'Alternate needed')], max_length=255),
        ),
    ]
