# Generated by Django 2.2.28 on 2023-03-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0196_remove_registration_already_in_slack_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='previous_season_alternate',
        ),
    ]
