# Generated by Django 2.2.28 on 2023-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0197_remove_registration_previous_season_alternate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='slack_username',
        ),
    ]
