services:
  web:
    image: ghcr.io/lichess4545/litour-web:latest
    env_file: ".env"
    networks:
      - caddy
      - litour
    # ports:
    #   - "8000:8000"

  apiworker:
    image: ghcr.io/lichess4545/litour-api-worker:latest
    env_file: ".env"
    environment:
      HELTOUR_ENV: STAGING
      HELTOUR_APP: api_worker
    depends_on:
      - postgres
    networks:
      - litour

  celery:
    image: ghcr.io/lichess4545/litour-celery:latest
    env_file: ".env"
    networks:
      - litour

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: heltour
      POSTGRES_USER: heltour
      POSTGRES_PASSWORD: heltour_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heltour"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - litour

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - litour

  mailpit:
    image: axllent/mailpit:v1.24.1
    restart: unless-stopped
    networks:
      - litour

volumes:
  postgres_data:
    name: litour_postgres_data
  redis_data:
    name: litour_redis_data

networks:
  caddy:
    external: true
  litour:
    driver: bridge
